---
title:
author:
date:
output: html_document
params:
  sequenceName: '1'
  compName: '1'
  bestFit: '1'
  runDate: '1'
  loopCounter: '1'
  parserVersion: '1'
  markdownVersion: '1'
  outfile: '1'
---

```{r setup, include=FALSE}
      # tkmessageBox(title = "Load .Rmd", message = 'sparkyFit24.10.Rmd', icon="warning", type="ok")
knitr::opts_chunk$set(echo = TRUE)
printHeader <- params$loopCounter
      # tkmessageBox(title = "Load .Rmd", message = 'sparkyFit24.10.Rmd', icon="warning", type="ok")


```

```{r header text, echo=FALSE, results='asis', eval=printHeader}

cat("# Sparky fit report for sequence ", params$sequenceName,
    "\n Generated by Spokas lab on ",
    params$runDate,
    "using", "<b>", params$parserVersion, "</b> and <b>", params$markdownVersion, "</b>\n\n\n",
    "Fit data saved to:\n\n", params$outfile)
cat("<hr>")

```


```{r system info text, echo=FALSE, results='asis', eval=printHeader}

cat("### System info:\n",
    "\n Headspace analysis by HP5890 (ECD, TCD, FID).",
    "\n\n<b>ECD:</b> Haysep N 30m\n",
    "\n\n<b>TCD:</b> Mole Sieve 30m\n",
    "\n\n<b>FID:</b> Porapak Q 30m\n\n\n",
    "Uses Cook's Distance [<i>stats::cooks.distance()</i>] to exclude influential points from the calibration. Here we use
    Cook's Distance > 4 / number of points to identify influential points.")
```

***

\

\

<h2><center>**Calibration results for `r compName` vrs `r bestFit@var`**</center></h2>

\

```{r notes, echo=FALSE}



```


```{r library, echo=FALSE}

# data wrangling

suppressMessages(library(dplyr))
suppressMessages(library(tidyr))

# data output

suppressMessages(library(kableExtra))
suppressMessages(library(xtable))

# graphics output

suppressMessages(library(ggplot2))
suppressMessages(library(ggtext))
suppressMessages(library(ggsci))
#suppressMessages(library(gridExtra))
#suppressMessages(library(scales))

```


```{r functions, echo=FALSE}

round2 <- function(x, n) {
  z <- NULL
  z_frac <- NULL
  z <- abs(x)*10^n
  z
  z_frac <- z - trunc(z)
  z_frac
  z_frac <- round(z_frac, digits = 2)
  for (i in 1:length(z)){
    if (z_frac[i] >= 0.5) { # Couldn't get if condition to apply to each element of z_frac
      z[i] <- trunc(z)[i] + 1
    }else{
      z[i] <- trunc(z)[i]
    }
    z[i] <- z[i]/10^n
    z[i]*sign(x[i])
  }
  return(z)
} # end of round2

trimWhiteSpace <- function(x) {
  x <- sub("^\\s+", "", x) # trim leading white spaces
  x <- sub("\\s+$", "", x) # trim trailing white spaces
  return(x)  
} # end of trimWhiteSpace

```


```{r ggsci palettes, echo=FALSE}

d3 <- list()
Npal <- length(pal_d3("category20")(20))
for (i in 1:Npal) {
  d3[[i]] <- pal_d3("category20")(20)[i]
}

uchicago <- list()
Npal <- length(pal_uchicago()(9))
for (i in 1:Npal) {
  uchicago[[i]] <- pal_uchicago()(9)[i]
}

uchicago_l <- list()
Npal <- length(pal_uchicago("light")(9))
for (i in 1:Npal) {
  uchicago_l[[i]] <- pal_uchicago("light")(9)[i]
}

```


```{r plot model, echo=FALSE}

#  print(paste("plotModel: [", bestFit@compound, "]"))
  
  x0 <- bestFit@data$x
  y0 <- bestFit@data$y
  x_max <- max(x0, na.rm = TRUE)
  y_max <- max(y0, na.rm = TRUE)
  allStds <- data.frame(x = x0, y = y0)  
  keepStds <- data.frame(x = x0[bestFit@cooksKeep], y = y0[bestFit@cooksKeep])
  modelName <- bestFit@compound
  corXY <- bestFit@cooks.rsq
  plotTitle <- paste("Cook's fit for", bestFit@compound)
  # pngName <- gsub("\\%", "pct", modelName)
  # pngPathname <- paste(resultsFolder, paste(pngName,".png", sep = "" ), sep = "\\")
  # 
  # png(pngPathname)
  g <- ggplot(allStds, aes(x = x, y = y, xmin = 0, ymin = 0)) +
    geom_smooth(formula = y ~ x, data = keepStds, method = "lm", linewidth = 1, color = "darkorange") +
    xlab(bestFit@var) +
    ylab(paste(bestFit@compound, " [", bestFit@compUnits, "]")) +
    ggtitle(plotTitle) +
    theme(plot.title = element_text(size = 15, face = "bold", hjust = 0.5)) +
    annotate("text", label = paste("rsq =", round(corXY, 5)),
             x = 0.15 * x_max, y = 0.75 * y_max, size = 5, hjust = "left") +
    annotate("text", label = paste("p-value =", round(as.numeric(bestFit@cooks.pValue), 3)),
             x = 0.15 * x_max, y = 0.70 * y_max, size = 5, hjust = "left") +
    # annotate("text", label = paste("slope =", round(as.numeric(bestFit@cooks.lm$coefficients[2]), 3)),
    #          x = 0.15 * x_max, y = 0.65 * y_max, size = 5, hjust = "left") +
    # annotate("text", label = paste("inter =", round(as.numeric(bestFit@cooks.lm$coefficients[1]), 3)),
    #          x = 0.15 * x_max, y = 0.60 * y_max, size = 5, hjust = "left") +
    annotate("text", label = paste("N =", nrow(keepStds), "of", nrow(allStds)),
             x = 0.15 * x_max, y = 0.55 * y_max, size = 5, hjust = "left")
  if (nrow(keepStds) < nrow(allStds)) {
    g <- g + geom_point(data = allStds, color = "red", size = 2)
  }
  g <- g + geom_point(data = keepStds, color = "royalblue4", size = 2)
  print(g)

```

\

\

```{r print fit results, echo=FALSE, results='asis'}

bestFit@cooks.lm %>%
  summary() %>%
  xtable(label = "") %>%
   kable(caption = paste("<b>Cook's regression summary for ", params$compName, " standards.  [", params$sequenceName, "]</b>", sep = ""), digits = 3, full_width = TRUE)

```

\

\

```{r print residuals, echo=FALSE, results='asis'}

      fit_std <- predict(bestFit@cooks.lm, data.frame(x = x0))
      resid_std <- fit_std - y0
      expect_std <- y0
      fitSum <- data.frame(bestFit@runOrder, expect_std, fit_std, resid_std, bestFit@cooks.distance)
      colnames(fitSum) <- c("Run order", paste("Expected values [", bestFit@compUnits, "]", sep = ""), paste("Fit values [", bestFit@compUnits, "]", sep = ""), "Residuals", "Cook's distance")

fitSum %>%
  kable(caption = paste("<b>Fit values and residuals for ", params$compName, " standards.  [", params$sequenceName, "] <br> Excluded standards are shown in red. Cook's Distance cutoff = ", round(as.numeric(bestFit@cooksDcutoff), 3), "</b>", sep = ""), digits = 3) %>%
  kable_styling("striped", full_width = TRUE) %>%
  row_spec(which(!bestFit@cooksKeep), bold = T, color = "red")



```
